dependencies:
    pre:
        - sudo - echo "deb http://www.vps.fmvz.usp.br/CRAN/bin/linux/debian jessie-cran34/" >> /etc/apt/sources.list
        - sudo apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'
        - sudo apt-get update
        - sudo apt-get install -y --no-install-recommends libssl-dev libssh2-1-dev libcurl4-openssl-dev pandoc zlib1g-dev libxml2-dev r-base r-base-dev

test:
    - echo 'Okay'
